project_id = "miabmzhoclzlvmyebzqq"

[functions.create-payment-link]
verify_jwt = false

[functions.setup-admin]
verify_jwt = false

[functions.scrape-product]
verify_jwt = false

[functions.ai-optimize-product]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.import-clothing]
verify_jwt = false
