import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.93.3";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

const products = [
  // T-Shirts (7)
  { name: "FTX Men Printed Hooded Neck Polyester Black T-Shirt", seller: "FTX", category: "T-Shirts", price: 180, original_price: 675, discount_percent: 73, rating: 4.1, review_count: 1247, short_description: "Stylish hooded t-shirt with trendy print for casual wear", description: "Stay stylish with this FTX hooded neck t-shirt made from premium polyester fabric. Features a trendy print design perfect for casual outings. Comfortable fit with ribbed cuffs and hem.", features: ["Hooded Neck", "Polyester Fabric", "Printed Design", "Regular Fit", "Machine Washable", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/m/y/xl-989-1-ftx-original-imahgkmm38gggj2j.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/m/y/l-989-1-ftx-original-imahgkmm38gggj2j.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/m/y/m-989-1-ftx-original-imahgkmm38gggj2j.jpeg?q=90"] },
  { name: "Try This Men Checkered Zip Neck Cotton Blend Brown White T-Shirt", seller: "Try This", category: "T-Shirts", price: 298, original_price: 999, discount_percent: 70, rating: 4.3, review_count: 2534, short_description: "Trendy checkered zip neck t-shirt in brown and white", description: "Elevate your casual style with this Try This checkered t-shirt featuring a unique zip neck design. Made from cotton blend for all-day comfort. Perfect for weekend outings and casual gatherings.", features: ["Zip Neck", "Cotton Blend", "Checkered Pattern", "Regular Fit", "Half Sleeves", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/k/n/m-64518810-try-this-resized-2-original-imahev3vmv63z92z.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/k/n/l-64518810-try-this-resized-2-original-imahev3vmv63z92z.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/k/n/xl-64518810-try-this-resized-2-original-imahev3vmv63z92z.jpeg?q=90"] },
  { name: "Magneto Men Printed Round Neck Pure Cotton Green T-Shirt", seller: "Magneto", category: "T-Shirts", price: 300, original_price: 1299, discount_percent: 76, rating: 4.2, review_count: 876, short_description: "Cool printed round neck t-shirt in vibrant green color", description: "Make a statement with this Magneto printed round neck t-shirt. Crafted from 100% pure cotton for maximum comfort. The vibrant green color with stylish print makes it perfect for summer days.", features: ["Round Neck", "Pure Cotton", "Printed Design", "Regular Fit", "Breathable Fabric", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/r/y/z/xl-583-flag-star-olive-green-magneto-original-imahkwzv3hncwzgx.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/r/y/z/l-583-flag-star-olive-green-magneto-original-imahkwzv3hncwzgx.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/r/y/z/m-583-flag-star-olive-green-magneto-original-imahkwzv3hncwzgx.jpeg?q=90"] },
  { name: "TRIPR Pack of 4 Men Solid Round Neck Cotton Blend Multicolor T-Shirt", seller: "TRIPR", category: "T-Shirts", price: 488, original_price: 1999, discount_percent: 75, rating: 4.0, review_count: 15234, short_description: "Value pack of 4 solid color round neck t-shirts", description: "Great value pack of 4 solid colored t-shirts from TRIPR. Made from soft cotton blend fabric. Includes Navy, Grey, Maroon, and Black colors. Perfect for everyday wear.", features: ["Pack of 4", "Round Neck", "Cotton Blend", "Solid Colors", "Regular Fit", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/e/7/xxl-tnv-gy-mr-blrnplaind164-tripr-original-imahgy2qrabpzhwt.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/e/7/xl-tnv-gy-mr-blrnplaind164-tripr-original-imahgy2qrabpzhwt.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/e/7/l-tnv-gy-mr-blrnplaind164-tripr-original-imahgy2qrabpzhwt.jpeg?q=90"] },
  { name: "Dennis Lingo Men Solid Slim Fit Cotton Navy Blue T-Shirt", seller: "Dennis Lingo", category: "T-Shirts", price: 349, original_price: 1499, discount_percent: 76, rating: 4.4, review_count: 3421, short_description: "Premium slim fit cotton t-shirt in navy blue", description: "Upgrade your basics with this Dennis Lingo slim fit t-shirt in classic navy blue. Made from 100% cotton for breathable comfort. Slim fit design offers a modern silhouette.", features: ["Slim Fit", "100% Cotton", "Solid Pattern", "Round Neck", "Half Sleeves", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/8/o/u/l-ts124-vebnor-original-imahjkvzykhb59wr.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/8/o/u/m-ts124-vebnor-original-imahjkvzykhb59wr.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/8/o/u/xl-ts124-vebnor-original-imahjkvzykhb59wr.jpeg?q=90"] },
  { name: "Roadster Men Printed Round Neck Cotton White T-Shirt", seller: "Roadster", category: "T-Shirts", price: 279, original_price: 899, discount_percent: 68, rating: 4.3, review_count: 5672, short_description: "Classic printed white t-shirt for everyday comfort", description: "Roadster's printed round neck t-shirt in white is a wardrobe essential. Made from soft cotton fabric. Features a stylish graphic print that adds character to your casual look.", features: ["Round Neck", "Cotton Fabric", "Printed Design", "Regular Fit", "Machine Washable", "Available Sizes: S, M, L, XL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/f/i/o/m-auska-04098-ausk-original-imahk46ghngdsbvd.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/f/i/o/l-auska-04098-ausk-original-imahk46ghngdsbvd.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/f/i/o/xl-auska-04098-ausk-original-imahk46ghngdsbvd.jpeg?q=90"] },
  { name: "HRX by Hrithik Roshan Men Solid Round Neck Grey T-Shirt", seller: "HRX", category: "T-Shirts", price: 399, original_price: 1299, discount_percent: 69, rating: 4.5, review_count: 8934, short_description: "Premium solid grey t-shirt by HRX", description: "Designed for the active lifestyle, this HRX solid grey t-shirt is crafted from moisture-wicking fabric. Perfect for workouts and casual wear alike. Features anti-odor technology.", features: ["Round Neck", "Moisture Wicking", "Anti-odor Technology", "Regular Fit", "Quick Dry", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/q/d/m/s-t674-nb-party07-garbly-original-imahjc57tdwfwruz.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/q/d/m/m-t674-nb-party07-garbly-original-imahjc57tdwfwruz.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/q/d/m/l-t674-nb-party07-garbly-original-imahjc57tdwfwruz.jpeg?q=90"] },

  // Polo T-Shirts (5)
  { name: "AUSK Men Checkered Polo Neck Cotton Blend Black Grey T-Shirt", seller: "AUSK", category: "Polo T-Shirts", price: 258, original_price: 1499, discount_percent: 82, rating: 4.1, review_count: 4523, short_description: "Premium checkered polo t-shirt in black and grey", description: "Classic polo style meets modern fashion with this AUSK checkered polo neck t-shirt. Made from soft cotton blend fabric for all-day comfort. The black and grey combination is versatile for any occasion.", features: ["Polo Neck", "Cotton Blend", "Checkered Pattern", "Regular Fit", "Button Placket", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/b/u/l/xxl-auska-04099-ausk-original-imahk46gzvygw8eg.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/b/u/l/xl-auska-04099-ausk-original-imahk46gzvygw8eg.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/b/u/l/l-auska-04099-ausk-original-imahk46gzvygw8eg.jpeg?q=90"] },
  { name: "QOWL Men Colorblock Polo Neck Cotton Blend White T-Shirt", seller: "QOWL", category: "Polo T-Shirts", price: 230, original_price: 1299, discount_percent: 82, rating: 4.0, review_count: 2341, short_description: "Stylish colorblock polo in classic white", description: "Stand out with this QOWL colorblock polo t-shirt. Features a trendy color-blocked design on a clean white base. Made from breathable cotton blend perfect for summer.", features: ["Polo Neck", "Cotton Blend", "Colorblock Design", "Regular Fit", "Half Sleeves", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/a/9/o/m-t67-white-qowl-original-imahktgbgvxcxw4g.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/a/9/o/l-t67-white-qowl-original-imahktgbgvxcxw4g.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/a/9/o/xl-t67-white-qowl-original-imahktgbgvxcxw4g.jpeg?q=90"] },
  { name: "AUSK Men Striped Polo Neck Cotton Blend Brown Black T-Shirt", seller: "AUSK", category: "Polo T-Shirts", price: 258, original_price: 1499, discount_percent: 82, rating: 4.2, review_count: 3456, short_description: "Elegant striped polo in brown and black", description: "Elevate your polo game with this AUSK striped polo t-shirt. The brown and black stripe combination offers a sophisticated look. Cotton blend fabric ensures comfort throughout the day.", features: ["Polo Neck", "Cotton Blend", "Striped Pattern", "Regular Fit", "Ribbed Collar", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/m/8/xl-04052-aoosh-original-imahhy5sxf9cvcf3.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/m/8/l-04052-aoosh-original-imahhy5sxf9cvcf3.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/m/8/m-04052-aoosh-original-imahhy5sxf9cvcf3.jpeg?q=90"] },
  { name: "HOLDIT Men Printed Polo Neck Polyester Blue T-Shirt", seller: "HOLDIT", category: "Polo T-Shirts", price: 286, original_price: 999, discount_percent: 71, rating: 3.9, review_count: 1876, short_description: "Printed polo t-shirt in vibrant blue", description: "Add a pop of color to your wardrobe with this HOLDIT printed polo t-shirt. Made from durable polyester fabric with a bold print design. The vibrant blue color is perfect for casual summer days.", features: ["Polo Neck", "Polyester Fabric", "Printed Design", "Regular Fit", "Button Placket", "Available Sizes: M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/shopsy-t-shirt/r/v/5/l-sy-ts-3107-b-teal-holdit-original-imahkmx4hgsejzm6.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/shopsy-t-shirt/r/v/5/xl-sy-ts-3107-b-teal-holdit-original-imahkmx4hgsejzm6.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/shopsy-t-shirt/r/v/5/xxl-sy-ts-3107-b-teal-holdit-original-imahkmx4hgsejzm6.jpeg?q=90"] },
  { name: "Dam Men Striped Polo Neck Polyester Grey White T-Shirt", seller: "Dam", category: "Polo T-Shirts", price: 191, original_price: 499, discount_percent: 61, rating: 4.0, review_count: 5632, short_description: "Classic striped polo in grey and white", description: "Timeless style meets comfort with this Dam striped polo t-shirt. The grey and white striped design is classic and versatile. Made from lightweight polyester for easy care.", features: ["Polo Neck", "Polyester Fabric", "Striped Pattern", "Regular Fit", "Lightweight", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/x/5/3/s-hs-grey-polo-vertical-dam-original-imahbhg2cywgzuv8.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/x/5/3/m-hs-grey-polo-vertical-dam-original-imahbhg2cywgzuv8.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/x/5/3/l-hs-grey-polo-vertical-dam-original-imahbhg2cywgzuv8.jpeg?q=90"] },

  // Oversized T-Shirts (5)
  { name: "EYEBOGLER Men Oversized Printed Round Neck Cotton Black T-Shirt", seller: "EYEBOGLER", category: "Oversized T-Shirts", price: 329, original_price: 1499, discount_percent: 78, rating: 4.1, review_count: 3245, short_description: "Trendy oversized printed t-shirt in black", description: "Rock the oversized look with this EYEBOGLER printed t-shirt. Features a relaxed drop shoulder design with bold graphic print. 100% cotton for ultimate comfort. Perfect for streetwear styling.", features: ["Oversized Fit", "Drop Shoulder", "100% Cotton", "Printed Design", "Round Neck", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/m/y/xl-989-1-ftx-original-imahgkmm38gggj2j.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/m/y/l-989-1-ftx-original-imahgkmm38gggj2j.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/m/y/m-989-1-ftx-original-imahgkmm38gggj2j.jpeg?q=90"] },
  { name: "Bewakoof Men Heavy Oversized Acid Washed Cotton Olive T-Shirt", seller: "Bewakoof", category: "Oversized T-Shirts", price: 449, original_price: 1299, discount_percent: 65, rating: 4.3, review_count: 7823, short_description: "Heavy oversized acid washed t-shirt in olive", description: "Bewakoof's signature heavy oversized t-shirt with acid wash finish. Made from 240 GSM cotton for a substantial feel. The olive color with acid wash gives a rugged, trendy look.", features: ["Heavy Oversized Fit", "240 GSM Cotton", "Acid Washed", "Drop Shoulder", "Round Neck", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/r/y/z/xl-583-flag-star-olive-green-magneto-original-imahkwzv3hncwzgx.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/r/y/z/l-583-flag-star-olive-green-magneto-original-imahkwzv3hncwzgx.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/r/y/z/m-583-flag-star-olive-green-magneto-original-imahkwzv3hncwzgx.jpeg?q=90"] },
  { name: "Urban Monkey Oversized Typography Print White T-Shirt", seller: "Urban Monkey", category: "Oversized T-Shirts", price: 399, original_price: 999, discount_percent: 60, rating: 4.4, review_count: 4521, short_description: "Bold typography print oversized tee in white", description: "Express yourself with this Urban Monkey oversized t-shirt featuring bold typography print. Premium cotton fabric with a relaxed, roomy fit. Perfect for layering or wearing solo.", features: ["Oversized Fit", "Typography Print", "Premium Cotton", "Relaxed Cut", "Half Sleeves", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/k/n/m-64518810-try-this-resized-2-original-imahev3vmv63z92z.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/k/n/l-64518810-try-this-resized-2-original-imahev3vmv63z92z.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/k/n/xl-64518810-try-this-resized-2-original-imahev3vmv63z92z.jpeg?q=90"] },
  { name: "CHKOKKO Men Oversized Solid Cotton Blend Charcoal Grey T-Shirt", seller: "CHKOKKO", category: "Oversized T-Shirts", price: 359, original_price: 1199, discount_percent: 70, rating: 4.2, review_count: 2134, short_description: "Premium oversized solid tee in charcoal grey", description: "CHKOKKO's oversized solid t-shirt in charcoal grey is a minimalist's dream. Made from soft cotton blend with a generous cut. The neutral color pairs effortlessly with any bottoms.", features: ["Oversized Fit", "Cotton Blend", "Solid Color", "Drop Shoulder", "Round Neck", "Available Sizes: M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/8/o/u/l-ts124-vebnor-original-imahjkvzykhb59wr.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/8/o/u/xl-ts124-vebnor-original-imahjkvzykhb59wr.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/8/o/u/xxl-ts124-vebnor-original-imahjkvzykhb59wr.jpeg?q=90"] },
  { name: "NOBERO Men Oversized Graphic Print Cotton Blend Beige T-Shirt", seller: "NOBERO", category: "Oversized T-Shirts", price: 499, original_price: 1599, discount_percent: 68, rating: 4.5, review_count: 6234, short_description: "Graphic print oversized tee in trendy beige", description: "NOBERO's graphic print oversized t-shirt in beige brings artistic flair to your wardrobe. Premium cotton blend with a relaxed silhouette. The subtle graphic print adds character without being loud.", features: ["Oversized Fit", "Graphic Print", "Cotton Blend", "Relaxed Silhouette", "Crew Neck", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/f/i/o/m-auska-04098-ausk-original-imahk46ghngdsbvd.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/f/i/o/l-auska-04098-ausk-original-imahk46ghngdsbvd.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/f/i/o/xl-auska-04098-ausk-original-imahk46ghngdsbvd.jpeg?q=90"] },

  // Summer Shirts (5)
  { name: "Dennis Lingo Men Solid Slim Fit Cotton Casual Shirt White", seller: "Dennis Lingo", category: "Summer Shirts", price: 479, original_price: 1599, discount_percent: 70, rating: 4.3, review_count: 12456, short_description: "Classic white cotton casual shirt for summer", description: "Dennis Lingo's white cotton casual shirt is a summer essential. Made from breathable cotton fabric with a slim fit design. Features a spread collar and full button placket.", features: ["Slim Fit", "100% Cotton", "Spread Collar", "Full Sleeves", "Machine Washable", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/a/9/o/m-t67-white-qowl-original-imahktgbgvxcxw4g.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/a/9/o/l-t67-white-qowl-original-imahktgbgvxcxw4g.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/a/9/o/xl-t67-white-qowl-original-imahktgbgvxcxw4g.jpeg?q=90"] },
  { name: "Allen Solly Men Checkered Regular Fit Casual Shirt Sky Blue", seller: "Allen Solly", category: "Summer Shirts", price: 649, original_price: 1899, discount_percent: 65, rating: 4.4, review_count: 8765, short_description: "Checkered casual shirt in refreshing sky blue", description: "Allen Solly's checkered casual shirt in sky blue brings a fresh, summery vibe. Made from premium cotton for all-day comfort. Regular fit with button-down collar.", features: ["Regular Fit", "Cotton Fabric", "Checkered Pattern", "Button-Down Collar", "Chest Pocket", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/m/8/xl-04052-aoosh-original-imahhy5sxf9cvcf3.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/m/8/l-04052-aoosh-original-imahhy5sxf9cvcf3.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/m/8/m-04052-aoosh-original-imahhy5sxf9cvcf3.jpeg?q=90"] },
  { name: "Peter England Men Printed Cotton Linen Casual Shirt Beige", seller: "Peter England", category: "Summer Shirts", price: 599, original_price: 1799, discount_percent: 66, rating: 4.5, review_count: 6543, short_description: "Printed cotton linen shirt in elegant beige", description: "Peter England's cotton linen casual shirt in beige is the epitome of summer dressing. The cotton-linen blend provides natural breathability. Printed design adds a touch of sophistication.", features: ["Regular Fit", "Cotton Linen Blend", "Printed Design", "Spread Collar", "Full Button Placket", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/shopsy-t-shirt/r/v/5/l-sy-ts-3107-b-teal-holdit-original-imahkmx4hgsejzm6.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/shopsy-t-shirt/r/v/5/xl-sy-ts-3107-b-teal-holdit-original-imahkmx4hgsejzm6.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/shopsy-t-shirt/r/v/5/xxl-sy-ts-3107-b-teal-holdit-original-imahkmx4hgsejzm6.jpeg?q=90"] },
  { name: "VeBNoR Men Solid Half Sleeve Cotton Casual Shirt Navy Blue", seller: "VeBNoR", category: "Summer Shirts", price: 329, original_price: 999, discount_percent: 67, rating: 4.0, review_count: 4321, short_description: "Solid navy blue half sleeve casual shirt", description: "VeBNoR's solid navy blue half sleeve shirt is perfect for hot summer days. Made from lightweight cotton for maximum breathability. The half sleeve design keeps you cool and stylish.", features: ["Regular Fit", "Cotton Fabric", "Solid Pattern", "Half Sleeves", "Spread Collar", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/x/5/3/s-hs-grey-polo-vertical-dam-original-imahbhg2cywgzuv8.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/x/5/3/m-hs-grey-polo-vertical-dam-original-imahbhg2cywgzuv8.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/x/5/3/l-hs-grey-polo-vertical-dam-original-imahbhg2cywgzuv8.jpeg?q=90"] },
  { name: "Campus Sutra Men Striped Cotton Casual Shirt Light Green", seller: "Campus Sutra", category: "Summer Shirts", price: 449, original_price: 1399, discount_percent: 67, rating: 4.2, review_count: 3456, short_description: "Striped cotton shirt in refreshing light green", description: "Campus Sutra's striped casual shirt in light green brings a fresh summer feel. Made from pure cotton with a comfortable regular fit. The vertical stripe pattern adds a touch of elegance.", features: ["Regular Fit", "Pure Cotton", "Striped Pattern", "Band Collar", "Full Sleeves", "Available Sizes: S, M, L, XL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/q/d/m/s-t674-nb-party07-garbly-original-imahjc57tdwfwruz.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/q/d/m/m-t674-nb-party07-garbly-original-imahjc57tdwfwruz.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/q/d/m/l-t674-nb-party07-garbly-original-imahjc57tdwfwruz.jpeg?q=90"] },

  // Half Pants (5)
  { name: "Wearhouse Men Solid Grey Chino Shorts", seller: "Wearhouse", category: "Half Pants", price: 499, original_price: 1299, discount_percent: 61, rating: 4.3, review_count: 3214, short_description: "Classic grey chino shorts for casual comfort", description: "Wearhouse's solid grey chino shorts are a summer wardrobe essential. Made from premium cotton twill with a comfortable mid-rise waist. Features side pockets and a clean, polished look.", features: ["Regular Fit", "Cotton Twill", "Solid Pattern", "Mid Rise", "Side Pockets", "Available Sizes: 28, 30, 32, 34, 36, 38"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/short/c/o/h/36-whgmbsh04-wearhouse-original-imahjzhxqy8q5xgq.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/c/o/h/34-whgmbsh04-wearhouse-original-imahjzhxqy8q5xgq.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/c/o/h/32-whgmbsh04-wearhouse-original-imahjzhxqy8q5xgq.jpeg?q=90"] },
  { name: "INDICLUB Pack of 3 Men Solid Casual Shorts Multicolor", seller: "INDICLUB", category: "Half Pants", price: 401, original_price: 1999, discount_percent: 79, rating: 4.0, review_count: 7654, short_description: "Value pack of 3 solid casual shorts", description: "INDICLUB's pack of 3 solid casual shorts offers great value for everyday wear. Includes Dark Blue, Light Green, and Silver colors. Made from breathable fabric with an elastic waistband.", features: ["Pack of 3", "Regular Fit", "Elastic Waistband", "Side Pockets", "Breathable Fabric", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/short/b/2/f/m-ic-n2454749-indiclub-original-imagp4c4spha33gh.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/b/2/f/l-ic-n2454749-indiclub-original-imagp4c4spha33gh.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/b/2/f/xl-ic-n2454749-indiclub-original-imagp4c4spha33gh.jpeg?q=90"] },
  { name: "DHIVIZ Men Solid Grey Regular Shorts", seller: "DHIVIZ", category: "Half Pants", price: 154, original_price: 799, discount_percent: 80, rating: 3.8, review_count: 2345, short_description: "Comfortable solid grey shorts for everyday wear", description: "DHIVIZ's solid grey regular shorts are designed for maximum comfort. Features an elastic waistband with drawstring for a perfect fit. Lightweight and breathable, ideal for hot summer days.", features: ["Regular Fit", "Elastic Waistband", "Drawstring Closure", "Side Pockets", "Lightweight", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/short/h/u/t/xxl-sh-gyk-dhiviz-original-imahkd6mhuezczwe.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/h/u/t/xl-sh-gyk-dhiviz-original-imahkd6mhuezczwe.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/h/u/t/l-sh-gyk-dhiviz-original-imahkd6mhuezczwe.jpeg?q=90"] },
  { name: "SHREE JAI Pack of 3 Men Printed Multicolor Regular Shorts", seller: "SHREE JAI", category: "Half Pants", price: 259, original_price: 1299, discount_percent: 80, rating: 4.1, review_count: 5432, short_description: "Pack of 3 printed shorts in vibrant colors", description: "SHREE JAI's pack of 3 printed regular shorts features vibrant patterns and colors. Made from soft cotton blend with an elastic waistband. Perfect for lounging at home or casual outings.", features: ["Pack of 3", "Cotton Blend", "Printed Patterns", "Elastic Waistband", "Regular Fit", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/short/1/s/r/l-sj-king-mens-shree-jai-original-imah7zfm7kxgwvkj.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/1/s/r/xl-sj-king-mens-shree-jai-original-imah7zfm7kxgwvkj.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/1/s/r/xxl-sj-king-mens-shree-jai-original-imah7zfm7kxgwvkj.jpeg?q=90"] },
  { name: "STI Pack of 2 Men Self Design Multicolor Regular Shorts", seller: "sti", category: "Half Pants", price: 404, original_price: 1998, discount_percent: 79, rating: 4.2, review_count: 8765, short_description: "Pack of 2 self design shorts in multicolor", description: "STI's pack of 2 self design regular shorts combines style with comfort. Features a subtle self design pattern in multiple colors. Elastic waistband with internal drawstring for adjustable fit.", features: ["Pack of 2", "Self Design", "Elastic Waistband", "Cotton Blend", "Regular Fit", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/short/a/j/l/s-combo-shorts-sti-original-imahgfszrzsgttgb.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/a/j/l/m-combo-shorts-sti-original-imahgfszrzsgttgb.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/a/j/l/l-combo-shorts-sti-original-imahgfszrzsgttgb.jpeg?q=90"] },

  // Casual Shorts (5)
  { name: "Riksaw Pack of 2 Men Solid Dark Blue Black Regular Shorts", seller: "Riksaw", category: "Casual Shorts", price: 286, original_price: 999, discount_percent: 71, rating: 4.0, review_count: 3456, short_description: "Pack of 2 solid regular shorts in dark blue and black", description: "Riksaw's pack of 2 solid regular shorts in dark blue and black are perfect basics. Made from durable polyester cotton blend. Features an elastic waistband and side pockets.", features: ["Pack of 2", "Regular Fit", "Elastic Waistband", "Side Pockets", "Polyester Cotton Blend", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/shopsy-short/o/b/u/xxl-spy-s31-navy-black-regular-shorts-rusksun-men-original-imahkthbnvdbzprs.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/shopsy-short/o/b/u/xl-spy-s31-navy-black-regular-shorts-rusksun-men-original-imahkthbnvdbzprs.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/shopsy-short/o/b/u/l-spy-s31-navy-black-regular-shorts-rusksun-men-original-imahkthbnvdbzprs.jpeg?q=90"] },
  { name: "Urbano Fashion Men Solid Slim Fit Cotton Khaki Shorts", seller: "Urbano Fashion", category: "Casual Shorts", price: 449, original_price: 1299, discount_percent: 65, rating: 4.3, review_count: 5678, short_description: "Slim fit cotton shorts in classic khaki", description: "Urbano Fashion's slim fit khaki shorts are a wardrobe staple. Made from premium cotton with a modern slim fit. Features button and zip closure with belt loops for a polished casual look.", features: ["Slim Fit", "Premium Cotton", "Button & Zip Closure", "Belt Loops", "Side Pockets", "Available Sizes: 28, 30, 32, 34, 36"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/short/c/o/h/36-whgmbsh04-wearhouse-original-imahjzhxqy8q5xgq.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/c/o/h/34-whgmbsh04-wearhouse-original-imahjzhxqy8q5xgq.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/c/o/h/32-whgmbsh04-wearhouse-original-imahjzhxqy8q5xgq.jpeg?q=90"] },
  { name: "Maniac Men Solid Cotton Blend Charcoal Bermuda Shorts", seller: "Maniac", category: "Casual Shorts", price: 349, original_price: 999, discount_percent: 65, rating: 4.1, review_count: 2345, short_description: "Bermuda length shorts in charcoal grey", description: "Maniac's cotton blend bermuda shorts in charcoal offer a smart casual look. The knee-length cut is versatile and comfortable. Features side pockets and an elastic waistband with drawstring.", features: ["Regular Fit", "Cotton Blend", "Bermuda Length", "Elastic Waistband", "Drawstring", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/short/h/u/t/xxl-sh-gyk-dhiviz-original-imahkd6mhuezczwe.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/h/u/t/xl-sh-gyk-dhiviz-original-imahkd6mhuezczwe.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/h/u/t/l-sh-gyk-dhiviz-original-imahkd6mhuezczwe.jpeg?q=90"] },
  { name: "Highlander Men Printed Swim Shorts Navy Blue", seller: "Highlander", category: "Casual Shorts", price: 399, original_price: 1199, discount_percent: 66, rating: 4.2, review_count: 1234, short_description: "Printed swim shorts in navy blue", description: "Highlander's printed swim shorts in navy blue are perfect for beach days and pool parties. Made from quick-dry polyester with an elastic waistband. Features an internal mesh lining.", features: ["Regular Fit", "Quick Dry Polyester", "Mesh Lining", "Elastic Waistband", "Printed Design", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/short/1/s/r/l-sj-king-mens-shree-jai-original-imah7zfm7kxgwvkj.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/1/s/r/xl-sj-king-mens-shree-jai-original-imah7zfm7kxgwvkj.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/1/s/r/xxl-sj-king-mens-shree-jai-original-imah7zfm7kxgwvkj.jpeg?q=90"] },
  { name: "Jockey Men Solid Knit Sport Shorts Grey Melange", seller: "Jockey", category: "Casual Shorts", price: 549, original_price: 1099, discount_percent: 50, rating: 4.5, review_count: 9876, short_description: "Comfortable knit sport shorts in grey melange", description: "Jockey's knit sport shorts in grey melange are designed for active comfort. Super soft fabric with moisture management. Features a comfortable elastic waistband and functional pockets.", features: ["Regular Fit", "Knit Fabric", "Moisture Management", "Elastic Waistband", "Functional Pockets", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/short/a/j/l/s-combo-shorts-sti-original-imahgfszrzsgttgb.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/a/j/l/m-combo-shorts-sti-original-imahgfszrzsgttgb.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/a/j/l/l-combo-shorts-sti-original-imahgfszrzsgttgb.jpeg?q=90"] },

  // Full Pants (5)
  { name: "Dennis Lingo Men Solid Slim Fit Cotton Casual Trousers Navy", seller: "Dennis Lingo", category: "Full Pants", price: 599, original_price: 1999, discount_percent: 70, rating: 4.3, review_count: 7654, short_description: "Slim fit cotton casual trousers in navy blue", description: "Dennis Lingo's slim fit cotton trousers in navy are a versatile wardrobe essential. Made from premium cotton with a modern slim fit. Features zip fly with button closure and belt loops.", features: ["Slim Fit", "Premium Cotton", "Zip Fly Button Closure", "Belt Loops", "4 Pockets", "Available Sizes: 28, 30, 32, 34, 36, 38"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/b/u/l/xxl-auska-04099-ausk-original-imahk46gzvygw8eg.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/b/u/l/xl-auska-04099-ausk-original-imahk46gzvygw8eg.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/b/u/l/l-auska-04099-ausk-original-imahk46gzvygw8eg.jpeg?q=90"] },
  { name: "Allen Solly Men Regular Fit Cotton Blend Casual Trousers Beige", seller: "Allen Solly", category: "Full Pants", price: 749, original_price: 2299, discount_percent: 67, rating: 4.4, review_count: 5432, short_description: "Regular fit beige casual trousers for smart look", description: "Allen Solly's regular fit casual trousers in beige offer a smart casual look. Made from cotton blend for comfort and durability. Features a clean front with single pleat.", features: ["Regular Fit", "Cotton Blend", "Single Pleat", "Zip Fly Button Closure", "Belt Loops", "Available Sizes: 28, 30, 32, 34, 36, 38"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/a/9/o/m-t67-white-qowl-original-imahktgbgvxcxw4g.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/a/9/o/l-t67-white-qowl-original-imahktgbgvxcxw4g.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/a/9/o/xl-t67-white-qowl-original-imahktgbgvxcxw4g.jpeg?q=90"] },
  { name: "Roadster Men Slim Fit Stretchable Cotton Jogger Pants Olive", seller: "Roadster", category: "Full Pants", price: 449, original_price: 1499, discount_percent: 70, rating: 4.2, review_count: 8765, short_description: "Stretchable cotton jogger pants in olive green", description: "Roadster's stretchable cotton jogger pants in olive combine casual comfort with modern style. Features an elastic waistband with drawstring, ribbed ankle cuffs, and side pockets.", features: ["Slim Fit", "Stretchable Cotton", "Elastic Waistband", "Ribbed Cuffs", "Drawstring", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/r/y/z/xl-583-flag-star-olive-green-magneto-original-imahkwzv3hncwzgx.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/r/y/z/l-583-flag-star-olive-green-magneto-original-imahkwzv3hncwzgx.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/r/y/z/m-583-flag-star-olive-green-magneto-original-imahkwzv3hncwzgx.jpeg?q=90"] },
  { name: "Peter England Men Solid Cotton Chinos Charcoal Grey", seller: "Peter England", category: "Full Pants", price: 699, original_price: 1999, discount_percent: 65, rating: 4.5, review_count: 4321, short_description: "Solid cotton chinos in sophisticated charcoal grey", description: "Peter England's cotton chinos in charcoal grey are perfect for smart casual occasions. Made from premium cotton with a comfortable fit. Features clean front pockets and back welt pockets.", features: ["Slim Fit", "Premium Cotton", "Chino Style", "Flat Front", "4 Pockets", "Available Sizes: 28, 30, 32, 34, 36, 38"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/8/o/u/l-ts124-vebnor-original-imahjkvzykhb59wr.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/8/o/u/xl-ts124-vebnor-original-imahjkvzykhb59wr.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/8/o/u/xxl-ts124-vebnor-original-imahjkvzykhb59wr.jpeg?q=90"] },
  { name: "Highlander Men Regular Fit Cotton Cargo Pants Khaki", seller: "Highlander", category: "Full Pants", price: 549, original_price: 1699, discount_percent: 67, rating: 4.1, review_count: 6543, short_description: "Regular fit cotton cargo pants in khaki", description: "Highlander's cotton cargo pants in khaki offer rugged style with plenty of pocket space. Made from durable cotton with a regular fit. Features multiple cargo pockets and button fly.", features: ["Regular Fit", "Durable Cotton", "Cargo Pockets", "Button Fly", "Belt Loops", "Available Sizes: 28, 30, 32, 34, 36, 38"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/k/n/m-64518810-try-this-resized-2-original-imahev3vmv63z92z.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/k/n/l-64518810-try-this-resized-2-original-imahev3vmv63z92z.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/k/n/xl-64518810-try-this-resized-2-original-imahev3vmv63z92z.jpeg?q=90"] },

  // Cotton Lowers (5)
  { name: "Dollar Men Pack of 2 Solid Cotton Lounge Pants Navy Black", seller: "Dollar", category: "Cotton Lowers", price: 399, original_price: 1198, discount_percent: 66, rating: 4.0, review_count: 12345, short_description: "Pack of 2 comfortable cotton lounge pants", description: "Dollar's pack of 2 cotton lounge pants in navy and black are perfect for relaxing at home. Made from 100% cotton for softness and breathability. Features an elastic waistband with drawstring.", features: ["Pack of 2", "100% Cotton", "Elastic Waistband", "Drawstring Closure", "Side Pockets", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/e/7/xxl-tnv-gy-mr-blrnplaind164-tripr-original-imahgy2qrabpzhwt.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/e/7/xl-tnv-gy-mr-blrnplaind164-tripr-original-imahgy2qrabpzhwt.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/e/7/l-tnv-gy-mr-blrnplaind164-tripr-original-imahgy2qrabpzhwt.jpeg?q=90"] },
  { name: "VIMAL JONNEY Men Solid Cotton Blend Lower Charcoal Grey", seller: "VIMAL JONNEY", category: "Cotton Lowers", price: 249, original_price: 799, discount_percent: 68, rating: 3.9, review_count: 8765, short_description: "Comfortable cotton blend lower in charcoal grey", description: "VIMAL JONNEY's cotton blend lower in charcoal grey is perfect for everyday lounging. Features a comfortable elastic waistband and relaxed fit. Ideal for home wear or casual outings.", features: ["Regular Fit", "Cotton Blend", "Elastic Waistband", "Side Pockets", "Relaxed Fit", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/m/8/xl-04052-aoosh-original-imahhy5sxf9cvcf3.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/m/8/l-04052-aoosh-original-imahhy5sxf9cvcf3.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/m/8/m-04052-aoosh-original-imahhy5sxf9cvcf3.jpeg?q=90"] },
  { name: "Jockey Men Solid Cotton Jersey Lounge Pants Grey Melange", seller: "Jockey", category: "Cotton Lowers", price: 549, original_price: 1099, discount_percent: 50, rating: 4.5, review_count: 15678, short_description: "Premium cotton jersey lounge pants", description: "Jockey's cotton jersey lounge pants in grey melange offer premium comfort. Super soft jersey fabric with a relaxed fit. Features an elastic waistband and open bottom hem.", features: ["Relaxed Fit", "Cotton Jersey", "Elastic Waistband", "Open Bottom", "Side Pockets", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/shopsy-t-shirt/r/v/5/l-sy-ts-3107-b-teal-holdit-original-imahkmx4hgsejzm6.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/shopsy-t-shirt/r/v/5/xl-sy-ts-3107-b-teal-holdit-original-imahkmx4hgsejzm6.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/shopsy-t-shirt/r/v/5/xxl-sy-ts-3107-b-teal-holdit-original-imahkmx4hgsejzm6.jpeg?q=90"] },
  { name: "FFLIRTYGO Men Solid Cotton Pyjama Lower Navy Blue", seller: "FFLIRTYGO", category: "Cotton Lowers", price: 299, original_price: 999, discount_percent: 70, rating: 4.1, review_count: 6543, short_description: "Solid cotton pyjama lower in navy blue", description: "FFLIRTYGO's cotton pyjama lower in navy blue is your go-to loungewear. Made from soft cotton with a comfortable elastic waistband. Features a relaxed fit with side pockets.", features: ["Regular Fit", "100% Cotton", "Elastic Waistband", "Side Pockets", "Lightweight", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/x/5/3/s-hs-grey-polo-vertical-dam-original-imahbhg2cywgzuv8.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/x/5/3/m-hs-grey-polo-vertical-dam-original-imahbhg2cywgzuv8.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/x/5/3/l-hs-grey-polo-vertical-dam-original-imahbhg2cywgzuv8.jpeg?q=90"] },
  { name: "KILLER Men Solid Cotton Stretch Jogger Pants Black", seller: "KILLER", category: "Cotton Lowers", price: 499, original_price: 1499, discount_percent: 66, rating: 4.3, review_count: 4321, short_description: "Solid cotton stretch jogger pants in black", description: "KILLER's cotton stretch jogger pants in black combine style with comfort. Made from stretchable cotton blend with ribbed ankle cuffs. Features zip pockets and a drawstring waist.", features: ["Slim Fit", "Cotton Stretch", "Ribbed Cuffs", "Zip Pockets", "Drawstring Waist", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/m/y/xl-989-1-ftx-original-imahgkmm38gggj2j.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/m/y/l-989-1-ftx-original-imahgkmm38gggj2j.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/v/m/y/m-989-1-ftx-original-imahgkmm38gggj2j.jpeg?q=90"] },

  // Track Pants (5)
  { name: "HRX by Hrithik Roshan Men Solid Regular Fit Track Pants Navy", seller: "HRX", category: "Track Pants", price: 449, original_price: 1499, discount_percent: 70, rating: 4.4, review_count: 13456, short_description: "Comfortable regular fit track pants in navy", description: "HRX's regular fit track pants in navy are designed for workouts and casual wear. Made from moisture-wicking fabric with a comfortable elastic waistband. Features zip pockets.", features: ["Regular Fit", "Moisture Wicking", "Elastic Waistband", "Zip Pockets", "Quick Dry", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/q/d/m/s-t674-nb-party07-garbly-original-imahjc57tdwfwruz.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/q/d/m/m-t674-nb-party07-garbly-original-imahjc57tdwfwruz.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/q/d/m/l-t674-nb-party07-garbly-original-imahjc57tdwfwruz.jpeg?q=90"] },
  { name: "Adidas Men Solid Polyester Training Track Pants Black", seller: "Adidas", category: "Track Pants", price: 699, original_price: 2199, discount_percent: 68, rating: 4.6, review_count: 7654, short_description: "Performance training track pants in black", description: "Adidas training track pants in black are built for performance. Made from AEROREADY moisture-absorbing fabric. Features a tapered fit with zip pockets and elastic cuffs.", features: ["Tapered Fit", "AEROREADY Technology", "Zip Pockets", "Elastic Cuffs", "Drawstring Waist", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/f/i/o/m-auska-04098-ausk-original-imahk46ghngdsbvd.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/f/i/o/l-auska-04098-ausk-original-imahk46ghngdsbvd.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/f/i/o/xl-auska-04098-ausk-original-imahk46ghngdsbvd.jpeg?q=90"] },
  { name: "Puma Men Solid Slim Fit Track Pants Peacoat Blue", seller: "Puma", category: "Track Pants", price: 599, original_price: 1999, discount_percent: 70, rating: 4.4, review_count: 5432, short_description: "Slim fit track pants in peacoat blue", description: "Puma's slim fit track pants in peacoat blue offer a sporty yet stylish look. Made from dryCELL moisture-wicking fabric. Features Puma's iconic cat logo and zip pockets.", features: ["Slim Fit", "dryCELL Technology", "Zip Pockets", "Elastic Cuffs", "Cat Logo", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/b/u/l/xxl-auska-04099-ausk-original-imahk46gzvygw8eg.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/b/u/l/xl-auska-04099-ausk-original-imahk46gzvygw8eg.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/b/u/l/l-auska-04099-ausk-original-imahk46gzvygw8eg.jpeg?q=90"] },
  { name: "CHKOKKO Men Solid Dry Fit Track Pants Dark Grey", seller: "CHKOKKO", category: "Track Pants", price: 399, original_price: 1299, discount_percent: 69, rating: 4.2, review_count: 3456, short_description: "Dry fit track pants in dark grey", description: "CHKOKKO's dry fit track pants in dark grey are versatile for gym and casual wear. Made from moisture-wicking fabric with 4-way stretch. Features zip pockets and elastic waistband.", features: ["Regular Fit", "Dry Fit Fabric", "4-Way Stretch", "Zip Pockets", "Elastic Waistband", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/k/n/m-64518810-try-this-resized-2-original-imahev3vmv63z92z.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/k/n/l-64518810-try-this-resized-2-original-imahev3vmv63z92z.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/g/k/n/xl-64518810-try-this-resized-2-original-imahev3vmv63z92z.jpeg?q=90"] },
  { name: "Wildcraft Men Solid Quick Dry Track Pants Olive Green", seller: "Wildcraft", category: "Track Pants", price: 499, original_price: 1599, discount_percent: 68, rating: 4.3, review_count: 2345, short_description: "Quick dry track pants for outdoor activities", description: "Wildcraft's quick dry track pants in olive green are designed for outdoor enthusiasts. Made from lightweight quick-dry fabric. Features multiple pockets and an adjustable drawstring waist.", features: ["Regular Fit", "Quick Dry", "Lightweight", "Multiple Pockets", "Drawstring Waist", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/r/y/z/xl-583-flag-star-olive-green-magneto-original-imahkwzv3hncwzgx.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/r/y/z/l-583-flag-star-olive-green-magneto-original-imahkwzv3hncwzgx.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/r/y/z/m-583-flag-star-olive-green-magneto-original-imahkwzv3hncwzgx.jpeg?q=90"] },

  // Gym Wear Sets (3)
  { name: "FUAARK Men Solid Gym T-Shirt and Shorts Set Black", seller: "FUAARK", category: "Gym Wear", price: 499, original_price: 1999, discount_percent: 75, rating: 4.2, review_count: 3456, short_description: "Complete gym set with t-shirt and shorts", description: "FUAARK's gym t-shirt and shorts set in black is your complete workout solution. Made from moisture-wicking fabric with 4-way stretch. The t-shirt features a slim fit while shorts have an elastic waistband.", features: ["Complete Set", "Moisture Wicking", "4-Way Stretch", "Slim Fit Tee", "Elastic Waist Shorts", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/8/o/u/l-ts124-vebnor-original-imahjkvzykhb59wr.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/8/o/u/xl-ts124-vebnor-original-imahjkvzykhb59wr.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/8/o/u/xxl-ts124-vebnor-original-imahjkvzykhb59wr.jpeg?q=90"] },
  { name: "DECISIVE Men Solid Dry Fit Gym Tank Top and Shorts Set Grey", seller: "DECISIVE", category: "Gym Wear", price: 449, original_price: 1499, discount_percent: 70, rating: 4.1, review_count: 2345, short_description: "Gym tank top and shorts combo in grey", description: "DECISIVE's dry fit gym tank top and shorts set in grey is perfect for intense workouts. Made from lightweight dry fit fabric. The tank top features a racerback design and shorts have mesh panels.", features: ["Complete Set", "Dry Fit Fabric", "Racerback Tank", "Mesh Panels", "Quick Dry", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/short/h/u/t/xxl-sh-gyk-dhiviz-original-imahkd6mhuezczwe.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/h/u/t/xl-sh-gyk-dhiviz-original-imahkd6mhuezczwe.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/short/h/u/t/l-sh-gyk-dhiviz-original-imahkd6mhuezczwe.jpeg?q=90"] },
  { name: "REEBOK Men Performance Gym T-Shirt and Track Pants Set Navy", seller: "REEBOK", category: "Gym Wear", price: 799, original_price: 2499, discount_percent: 68, rating: 4.5, review_count: 5678, short_description: "Premium performance gym set in navy blue", description: "REEBOK's performance gym set includes a moisture-wicking t-shirt and comfortable track pants in navy. SPEEDWICK technology keeps you cool during intense workouts. Premium quality for serious athletes.", features: ["Complete Set", "SPEEDWICK Technology", "Moisture Wicking", "Zip Pockets on Pants", "Round Neck Tee", "Available Sizes: S, M, L, XL, XXL"], images: ["https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/q/d/m/s-t674-nb-party07-garbly-original-imahjc57tdwfwruz.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/q/d/m/m-t674-nb-party07-garbly-original-imahjc57tdwfwruz.jpeg?q=90","https://rukminim2.flixcart.com/image/800/1070/xif0q/t-shirt/q/d/m/l-t674-nb-party07-garbly-original-imahjc57tdwfwruz.jpeg?q=90"] },
];

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, serviceRoleKey, {
      auth: { autoRefreshToken: false, persistSession: false },
    });

    let inserted = 0;
    for (let i = 0; i < products.length; i++) {
      const p = products[i];
      const { data: productData, error: productError } = await supabase
        .from("products")
        .insert({
          name: p.name,
          seller: p.seller,
          category: p.category,
          price: p.price,
          original_price: p.original_price,
          rating: p.rating,
          review_count: p.review_count,
          short_description: p.short_description,
          description: p.description,
          features: p.features,
          stock: 100,
          free_delivery: true,
          is_visible: true,
          sort_order: i,
        })
        .select("id")
        .single();

      if (productError) {
        console.error(`Error inserting product ${i}:`, productError);
        continue;
      }

      // Insert images
      const imageRows = p.images.map((url, idx) => ({
        product_id: productData.id,
        image_url: url,
        sort_order: idx,
      }));

      const { error: imgError } = await supabase
        .from("product_images")
        .insert(imageRows);

      if (imgError) {
        console.error(`Error inserting images for product ${i}:`, imgError);
      }

      inserted++;
    }

    return new Response(
      JSON.stringify({ success: true, inserted, total: products.length }),
      { status: 200, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    console.error("Import error:", error);
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
